name: Herbert Reininger
favicon: null
layout_spectrum: 0.6035808597225696
typography_spectrum: 0.7193460697308183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9580708004068583
  lightness: 0.17921693483367562
  saturation: 0.5006196063477546
  rhythmicContrast: 0.05394879309460521
purpose: []
